### ISSUE TITLE
Production build is failing.

### ISSUE THREAD

**Issue by vincentpalita** [NathanWalker/angular-seed-advanced#112]
**Steps to reproduce and a minimal demo of the problem**
npm run serve.prod

**Current behavior**
Fails at finding @angular/router-deprecated. See error log below:

```
Error on fetch for @angular/router-deprecated.js at file:///Users/user/angular2-seed-advanced-master/node_modules/@angular/router-deprecated.js
    Loading dist/tmp/app/frameworks/core.framework/index.js
    Loading dist/tmp/main.web.js
    Error: ENOENT: no such file or directory, open '/Users/user/angular2-seed-advanced-master/node_modules/@angular/router-deprecated.js'
    at Error (native)
```

It makes the build fail.

**Expected/desired behavior**
It should build normally.

**Other information**
I added below code in the seed-advanced.config.ts file, and the build ran successfully:

```
this.SYSTEM_BUILDER_CONFIG.packages['@angular/router-deprecated'] = {
     defaultExtension: 'js',
     main: 'index.js'
};
```

I guess since the way of including modules has changed with the way of retrieving external modules 
`this.SYSTEM_CONFIG['packages'] = systemJsPackages();`
and also the fact that the parent seed has removed the include of @angular/router-deprecated in its packages definition the systemjs-builder isn't using that configuration well.

**Comment by NathanWalker** [comment]
Fixed on master now 👍

**Comment by vincentpalita** [comment]
@nathanwalker, again thank you!
Will check that soon.
Cheers

**Comment by zeeshanjan82** [comment]
@NathanWalker  How can I apply the fix on this advanced seed as I understand it has been fixed in master but after I download this advanced seed I still get this error: https://github.com/NathanWalker/angular2-seed-advanced/issues/126
