### ISSUE TITLE
Error in MultilingualService

### ISSUE THREAD

**Issue by dskaggs** [NathanWalker/angular-seed-advanced#3]
I followed the instructions in the "How To Start" section and all went without error until I ran `npm start`.

During the `build.js.dev` Gulp task, the following error was emitted:
`src/frameworks/i18n.framework/services/multilingual.service.ts(36,17): error TS2339: Property 'useStaticFilesLoader' does not exist on type 'TranslateService'.`

![npm-run-error](https://cloud.githubusercontent.com/assets/432500/13622533/5826453e-e56d-11e5-838b-086595ccec28.png)

**Comment by AaronJin2013** [comment]
I have the  error,too.

**Comment by NathanWalker** [comment]
Related to breaking changes in `1.10.0` https://github.com/NathanWalker/angular2-seed-advanced/issues/2

I have just pushed a change to lock it to `1.9.0` for now to prevent the `^` from updating you to the latest breaking change version. Please pull latest and try once more. Thanks for the heads up here @dskaggs and @AaronJin2013  :+1: 
https://github.com/NathanWalker/angular2-seed-advanced/commit/7929bdf4aeda5163d765606e3d8005e86cccd80c

If this fixes it for you, please close the issue :)

**Comment by NathanWalker** [comment]
Oh btw, it would be best to 'rm -rf node_modules' and then do a fresh npm install after pulling that latest commit.

**Comment by dskaggs** [comment]
I completely blew away the entire directory, cloned again and set it back up. Verified that ng2-translate in package.json set at 1.9.0 and I still get the same error on `npm start`

**Comment by NathanWalker** [comment]
@dskaggs Looking into it now. I'm just going to go ahead and update to latest `1.10.0` of ng2-translate. One moment...

**Comment by NathanWalker** [comment]
Ok @dskaggs I have updated to latest `ng2-translate` and have verified everything on my end.
I'm using node `v5.5.0` with npm `3.5.3` on a Mac.

All tests pass and web runs with no errors. {N} app always has a few TS warnings but everything runs well there too.

Blow away again and try this. Thanks for hanging in there, lemme know.

**Comment by dskaggs** [comment]
All good now. Thanks for whipping this out.

**Comment by NathanWalker** [comment]
Thanks again @dskaggs, Enjoy!
